models:
  - name: prep_adakami_statistics
    description: "adakami statistics preparation layer"
    columns:
      - name: disburse_amount_total
        description: "Nilai pendanaan yang tersalurkan sejak melakukan kegiatan usaha"
        data_tests:
          - not_null
      - name: disburse_amount_this_year
        description: "Nilai pendanaan yang tersalurkan pada tahun berjalan"
        data_tests:
          - not_null
      - name: outstanding_loan_principal_total
        description: "Jumlah Outstanding Pinjaman Total pinjaman yang sedang berjalan"
        data_tests:
          - not_null
      - name: borrower_count_total
        description: "Jumlah penerima dana sejak melakukan kegiatan usaha"
        data_tests:
          - not_null
      - name: disburse_amount_last_month
        description: "Nilai pendanaan yang tersalurkan di bulan terakhir"
        data_tests:
          - not_null
      - name: lender_count_total
        description: "Jumlah pemberi dana sejak melakukan kegiatan usaha"
        data_tests:
          - not_null
      - name: lender_count_year
        description: "Jumlah pemberi dana pada tahun berjalan"
        data_tests:
          - not_null
      - name: lender_count_month
        description: "Jumlah pemberi dana di bulan terakhir"
        data_tests:
          - not_null
      - name: borrower_count_year
        description: "Jumlah penerima dana pada tahun berjalan"
        data_tests:
          - not_null
      - name: borrower_count_month
        description: "Jumlah penerima dana di bulan terakhir"
        data_tests:
          - not_null
      - name: fetch_time
        description: "API fetchtime in UTC"
        data_tests:
          - not_null
      - name: data_period
        description: "data period date (from airflow execution date) in Jakarta Time"
        data_tests:
          - not_null         
      - name: dbt_processed_date
        description: "data processed by dbt"
        data_tests:
          - not_null
