models:
  - name: dim_customers
    description: "customer dimension data"
    columns:
      - name: customer_id
        description: "Primary key & unique identifier for customer data"
        data_tests:
          - unique
          - not_null
      - name: customer_name
        description: "Customer full name"
        data_tests:
          - not_null
      - name: email
        description: "Customer email"
        data_tests:
          - not_null
      - name: birth_date
        description: "Customer birthdate"
        data_tests:
          - not_null
      - name: phone_number
        description: "Customer active phone number"
        data_tests:
          - not_null
      - name: address
        description: "Customer current address"
      - name: join_date
        description: "Customer join date"
        data_tests:
          - not_null
      - name: created_at
        description: "Data creation date in postgres"
        data_tests:
          - not_null
      - name: updated_at
        description: "Data updated date in postgres"
        data_tests:
          - not_null
      - name: dbt_processed_date
        description: "dbt processed date"
        data_tests:
          - not_null

  - name: dim_products
    description: "products dimension data"
    columns:
      - name: product_id
        description: "Unique product identifier"
        data_tests:
          - unique
          - not_null
      - name: product_name
        description: "Product name"
        data_tests:
          - not_null
      - name: category_id
        description: "Category identifier"
        data_tests:
          - not_null
      - name: price
        description: "Product price per unit."
        data_tests:
          - not_null
      - name: created_at
        description: "Data creation date in postgres"
        data_tests:
          - not_null
      - name: updated_at
        description: "Data updated date in postgres"
        data_tests:
          - not_null
      - name: dbt_processed_date
        description: "dbt processed date"
        data_tests:
          - not_null

  - name: dim_category
    description: "product category dimensional data"
    columns:
      - name: category_id
        description: "Unique Category identifier"
        data_tests:
          - unique
          - not_null
      - name: category_name
        description: "Category name"
        data_tests:
          - not_null
      - name: dbt_processed_date
        description: "dbt processed date"
        data_tests:
          - not_null

  - name: fct_transactions
    description: "transaction fact data"
    columns:
      - name: transaction_id
        description: "Unique transaction identifier"
        data_tests:
          - unique
          - not_null
      - name: customer_id
        description: "Unique customer identifier, referencing to customers table's customer_id"
        data_tests:
          - not_null
      - name: product_id
        description: "Product code identifier"
        data_tests:
          - not_null
      - name: unit_price
        description: "Product unit price"
        data_tests:
          - not_null
      - name: quantity
        description: "Product quantity"
        data_tests:
          - not_null
      - name: total_amount
        description: "Total amount per transaction"
      - name: created_at
        description: "Data creation date in postgres"
        data_tests:
          - not_null
      - name: updated_at
        description: "Data updated date in postgres"
        data_tests:
          - not_null
      - name: dbt_processed_date
        description: "dbt processed date"
        data_tests:
          - not_null

  - name: fct_payments
    description: "payments fact data"
    columns:
      - name: payment_id
        description: "Unique payment identifier"
        data_tests:
          - unique
          - not_null
      - name: transaction_id
        description: "Unique transaction identifier, referencing to transactions table's trx_id"
        data_tests:
          - not_null
      - name: amount
        description: "Amount per payment"
        data_tests:
          - not_null
      - name: payment_method
        description: "Payment method used"
        data_tests:
          - accepted_values:
              values: ["e_wallet", "bank_transfer", "credit_card", "cash_on_delivery"]
      - name: created_at
        description: "Data creation date in postgres"
        data_tests:
          - not_null
      - name: updated_at
        description: "Data updated date in postgres"
        data_tests:
          - not_null
      - name: dbt_processed_date
        description: "dbt processed date"
        data_tests:
          - not_null
      
