models:
  - name: prep_customers
    description: "customer data preparation layer"
    columns:
      - name: customer_id
        description: "Primary key & unique identifier for customer data"
        data_tests:
          - unique
          - not_null
      - name: customer_name
        description: "Customer full name"
        data_tests:
          - not_null
      - name: email
        description: "Customer email"
        data_tests:
          - not_null
      - name: birth_date
        description: "Customer birthdate"
        data_tests:
          - not_null
      - name: phone_number
        description: "Customer active phone number"
        data_tests:
          - not_null
      - name: address
        description: "Customer current address"
      - name: join_date
        description: "Customer join date"
        data_tests:
          - not_null
      - name: created_at
        description: "Data creation date in postgres"
        data_tests:
          - not_null
      - name: updated_at
        description: "Data updated date in postgres"
        data_tests:
          - not_null
      - name: run_date
        description: "Data ingestion date from Postgres to BigQuery"
        data_tests:
          - not_null

  - name: prep_transactions
    description: "Transactions data preparation layer"
    columns:
      - name: transaction_id
        description: "Unique transaction identifier"
        data_tests:
          - unique
          - not_null
      - name: customer_id
        description: "Unique customer identifier, referencing to customers table's customer_id"
        data_tests:
          - not_null
      - name: product_id
        description: "Product code identifier"
        data_tests:
          - not_null
      - name: unit_price
        description: "Product unit price"
        data_tests:
          - not_null
      - name: quantity
        description: "Product quantity"
        data_tests:
          - not_null
      - name: total_amount
        description: "Total amount per transaction"
        data_tests:
          - not_null
      - name: created_at
        description: "Data creation date in postgres"
        data_tests:
          - not_null
      - name: updated_at
        description: "Data updated date in postgres"
        data_tests:
          - not_null
      - name: run_date
        description: "Data ingestion date from Postgres to BigQuery"
        data_tests:
          - not_null

  - name: prep_payments
    description: "Payment data preparation layer"
    columns:
      - name: payment_id
        description: "Unique payment identifier"
        data_tests:
          - unique
          - not_null
      - name: transaction_id
        description: "Unique transaction identifier, referencing to transactions table's trx_id"
        data_tests:
          - not_null
      - name: amount
        description: "Amount per payment"
        data_tests:
          - not_null
      - name: payment_method
        description: "Payment method used"
        data_tests:
          - accepted_values:
              values: ["E_WALLET", "BANK_TRANSFER", "CREDIT_CARD", "CASH_ON_DELIVERY"]
      - name: created_at
        description: "Data creation date in postgres"
        data_tests:
          - not_null
      - name: updated_at
        description: "Data updated date in postgres"
        data_tests:
          - not_null
      - name: run_date
        description: "Data ingestion date from Postgres to BigQuery"
        data_tests:
          - not_null

  - name: prep_payment_status
    description: "Payment status preparation layer"
    columns:
      - name: event_id
        description: "Unique event identifier."
        data_tests:
          - not_null
      - name: event_time
        description: "Time when the event occured."
        data_tests:
          - not_null
      - name: payment_id
        description: "Payment identifier."
        data_tests:
          - not_null
      - name: transaction_id
        description: "Transaction identifier."
        data_tests:
          - not_null
      - name: status
        description: "Payment status per payment_id."
        data_tests:
          - accepted_values:
              values: ["FAILED", "SUCCESS", "PENDING"]  
      - name: reason
        description: "Failure or Pending reason, null for Success."
      - name: ingestion_time
        description: "Ingestion time to BigQuery"
        data_tests:
          - not_null
  
  - name: prep_products
    description: "products data preparation layer"
    columns:
      - name: product_id
        description: "Unique product identifier"
        data_tests:
          - not_null
      - name: product_name
        description: "Product name"
        data_tests:
          - not_null
      - name: category_id
        description: "Category identifier"
        data_tests:
          - not_null
      - name: category_name
        description: "Category name"
        data_tests:
          - not_null
      - name: price
        description: "Product price per unit."
        data_tests:
          - not_null
      - name: created_at
        description: "Data creation date in BigQuery"
        data_tests:
          - not_null
      - name: updated_at
        description: "Data updated date in BigQuery"
        data_tests:
          - not_null
      

  