models:
  - name: customer_segmentation
    description: "Customer age group and loyalty status - customer market analysis"
    columns:
      - name: customer_id
        description: "Primary key & unique identifier for customer data"
        data_tests:
          - unique
          - not_null
      - name: customer_name
        description: "Customer full name"
        data_tests:
          - not_null
      - name: email
        description: "Customer email"
        data_tests:
          - not_null
      - name: birth_date
        description: "Customer birthdate"
        data_tests:
          - not_null
      - name: phone_number
        description: "Customer active phone number"
        data_tests:
          - not_null
      - name: join_date
        description: "Customer join date"
        data_tests:
          - not_null
      - name: age_group
        description: "Customer age group, based on birth_date. Available groups are Under 18, 18-24, 25-34, 35-44, 45-54, 55-64, Above 65"
        data_tests:
          - accepted_values:
              values: ["Under 18", "18-24", "25-34", "35-44", "45-54", "55-64","Above 65"]
      - name: customer_status
        description: "Customer loyalty status-based on join_date where <=30: new, <=90:recent, <=365:active, >365 loyal"
        data_tests:
          - accepted_values:
              values: ["new", "recent", "active", "loyal"]
      - name: updated_at
        description: "Data updated date in postgres"
      - name: dbt_processed_date
        description: "dbt processed date"
        data_tests:
          - not_null

  - name: top_selling_products_daily
    description: "Top selling products"
    columns:
      - name: product_id
        description: "Unique product identifier"
        data_tests:
          - not_null
      - name: product_name
        description: "Product name"
        data_tests:
          - not_null
      - name: category_name
        description: "category_name"
        data_tests:
          - not_null
      - name: snapshot_date
        description: "date indicator"
        data_tests:
          - not_null
      - name: total_revenue
        description: "total revenue of product."
        data_tests:
          - not_null
      - name: dbt_processed_date
        description: "dbt processed date"
        data_tests:
          - not_null

  - name: payment_behavior_per_age_segment
    description: "Preferred payment method per age"
    columns:
      - name: age_group
        description: "Customer age group, based on birth_date. Available groups are Under 18, 18-24, 25-34, 35-44, 45-54, 55-64, Above 65"
        data_tests:
          - accepted_values:
              values: ["Under 18", "18-24", "25-34", "35-44", "45-54", "55-64","Above 65"]
      - name: customer_status
        description: "Customer loyalty status-based on join_date where <=30: new, <=90:recent, <=365:active, >365 loyal"
        data_tests:
          - accepted_values:
              values: ["new", "recent", "active", "loyal"]
      - name: payment_method
        description: "Payment method used"
        data_tests:
          - not_null
      - name: total_payment_count
        description: "Count of payment method usage"
        data_tests:
          - not_null
      - name: total_payment_values
        description: "Total of payment amount"
        data_tests:
          - not_null
      - name: dbt_processed_date
        description: "dbt processed date"
        data_tests:
          - not_null

  - name: category_performance_per_age_group
    description: "Category performance by age group, based on total revenue"
    columns:
      - name: age_group
        description: "Customer age group, based on birth_date. Available groups are Under 18, 18-24, 25-34, 35-44, 45-54, 55-64, Above 65"
        data_tests:
          - accepted_values:
              values: ["Under 18", "18-24", "25-34", "35-44", "45-54", "55-64","Above 65"]
      - name: category_name
        description: "category name"
        data_tests:
          - not_null
      - name: total_revenue
        description: "Total revenue per category"
      - name: dbt_processed_date
        description: "dbt processed date"
        data_tests:
          - not_null