table_name: products
description: "product details - static data"

clustering:
  enabled: true
  fields: 
    - product_id
    
schema:
  - name: product_id
    type: STRING
    mode: REQUIRED
    description: "Unique product identifier."
  - name: product_name
    type: STRING
    mode: REQUIRED
    description: "product name."
  - name: category_id
    type: STRING
    mode: REQUIRED
    description: "Category identifier."
  - name: category_name
    type: STRING
    mode: REQUIRED
    description: "Category name."
  - name: price
    type: FLOAT64
    mode: REQUIRED
    description: "Product price per unit."
  - name: created_at
    type: TIMESTAMP
    mode: REQUIRED
  - name: updated_at
    type: TIMESTAMP
    mode: REQUIRED