models:
  - name: prep_case_details
    description: "case details preparation layer"
    columns:
      - name: nomor_putusan
        description: "Nomor putusan kasus"
        data_tests:
          - not_null
          - unique
      - name: tingkat_proses
        description: "tingkat proses kasus"
        data_tests:
          - not_null
      - name: klasifikasi
        description: "klasifikasi kasus"
      - name: kata_kunci
        description: "Kata kunci kasus"
      - name: tahun
        description: "Tahun register kasus"
        data_tests:
          - not_null
      - name: tanggal_register
        description: "Tanggal register kasus"
      - name: lembaga_peradilan
        description: "Lembaga peradilan yang terlibat"
        data_tests:
          - not_null
      - name: jenis_lembaga_peradilan
        description: "Jenis lembaga peradilan yang terlibat"
        data_tests:
          - not_null
      - name: hakim_ketua
        description: "hakim ketua"
      - name: hakim_anggota
        description: "hakim anggota"
      - name: panitera
        description: "panitera"
      - name: amar
        description: "amar"
      - name: catatan_amar
        description: "catatan_amar" 
      - name: tanggal_musyawarah
        description: "tanggal musyawarah"
        data_tests:
          - not_null
      - name: tanggal_dibacakan
        description: "tanggal putusan dibacakan"
        data_tests:
          - not_null
      - name: pdf_link
        description: "link pdf hasil putusan"
        data_tests:
          - not_null
      - name: scrape_timestamp
        description: "Waktu scraping"
        data_tests:
          - not_null
      - name: putusan_ym
        description: "string YYYY-mm dari tanggal dibacakan"
        data_tests:
          - not_null      
      - name: ingestion_timestamp
        description: "Waktu ingestion kedalam bigquery"
        data_tests:
          - not_null
      - name: dbt_processed_date
        description: "data processed by dbt"
        data_tests:
          - not_null

  - name: prep_pdf_details
    description: "pdf details preparation layer"
    columns:
      - name: nomor_putusan
        description: "Nomor putusan kasus"
        data_tests:
          - not_null
          - unique
      - name: putusan_ym
        description: "data period, partitioned by register month and taken from logical date or airflow"
        data_tests:
          - not_null
      - name: nama_lengkap
        description: "first occurece of nama lengkap in pdf"
      - name: tempat_lahir
        description: "first occurence of tempat lahir in pdf"
      - name: umur_tanggal_lahir
        description: "first occurence of Umur & Tanggal Lahir in pdf"
      - name: jenis_kelamin
        description: "jenis kelamin in pdf"
      - name: kebangsaan
        description: "first occurence of tempat lahir in pdf"
      - name: agama
        description: "first occurence of agama in pdf"
      - name: pekerjaan
        description: "first occurence of pekerjaan in pdf"
      - name: tempat_tinggal
        description: "first occurence of tempat tinggal in pdf"
      - name: keputusan
        description: "takes the first 2 sentences of mengadili/menetapkan section in pdf"
      - name: ingestion_timestamp
        description: "Waktu ingestion kedalam bigquery"
        data_tests:
          - not_null
      - name: dbt_processed_date
        description: "data processed by dbt"
        data_tests:
          - not_null